# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50, verbose_name='mac')),
                ('endpoint', models.CharField(max_length=256, verbose_name='endpoint')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=50, verbose_name='mac')),
                ('ip', models.CharField(max_length=50, verbose_name='source ip')),
                ('timestamp', models.DateTimeField()),
                ('vrms_total', models.FloatField(verbose_name='Volt')),
            ],
        ),
    ]
